Update Jenkinsfile

diff --git a/forecast-flow-jenkins/local_repo/Jenkinsfile b/forecast-flow-jenkins/local_repo/Jenkinsfile
--- a/forecast-flow-jenkins/local_repo/Jenkinsfile
+++ b/forecast-flow-jenkins/local_repo/Jenkinsfile
@@ -11,6 +11,24 @@ pipeline {
             '''
       }
     }
+
+      stage('Environment Add') {
+      steps {
+        sh '''#!/usr/bin/env bash
+            set -euo pipefail
+            source /var/jenkins_home/venv/bin/activate 
+            if ctm environment saas::add sparkit replace-with-endpoint "replace-with-token" 2>add_err.log; then
+            echo "Environment added: sparkit"
+            exit 0 
+            fi 
+
+            if ctm environment saas::get "$ENV_NAME" >/dev/null 2>&1; then
+            echo "Environment already exists. Ignoring error and continuing."
+            exit 0
+            fi
+            '''
+      }
+    }
     
      stage('Build Workflow') {
       steps {
@@ -18,7 +36,7 @@ pipeline {
             set -euo pipefail
             source /var/jenkins_home/venv/bin/activate 
             mkdir -p workflows
-            cp /tmp/forecast-flow.json workflows/forecast-flow.json
+            cp /tmp/forecast-flow-jenkins/workflows/forecast-flow.json workflows/forecast-flow.json
             ctm build workflows/forecast-flow.json
             '''
       }
