Update Jenkinsfile-part-1

diff --git a/forecast-flow-jenkins/local_repo/Jenkinsfile-part-1 b/forecast-flow-jenkins/local_repo/Jenkinsfile-part-1
--- a/forecast-flow-jenkins/local_repo/Jenkinsfile-part-1
+++ b/forecast-flow-jenkins/local_repo/Jenkinsfile-part-1
@@ -27,7 +27,19 @@ pipeline {
         sh '''#!/usr/bin/env bash
             set -euo pipefail
             source /var/jenkins_home/venv/bin/activate 
-            ctm build /var/jenkins_home/workflows/forecast-flow-jenkins/workflows/forecast-flow.json /var/jenkins_home/workflows/forecast-flow-jenkins/local_repo/deploy_descriptor_failure.json
+            BUILD_OUTPUT=$(ctm build \
+        	/var/jenkins_home/workflows/forecast-flow-jenkins/workflows/forecast-flow.json \
+        	/var/jenkins_home/workflows/forecast-flow-jenkins/local_repo/deploy_descriptor_failure.json)
+
+      		echo "$BUILD_OUTPUT"
+
+      		# Fail if warnings exist
+      		if echo "$BUILD_OUTPUT" | grep -q '"warnings":'; then
+        		echo "❌ Build contains warnings. Failing pipeline."
+        		exit 1
+      		fi
+
+      		echo "✅ Build validation passed with no warnings."
             '''
 			}
 		}
